version: "3.1"

services:
  
  mongoose:
    build:
      context: ./
      target: buildimage
    command: bash -c "npm install && npm start"
    networks:
      development:
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app

  mongo:
    image: mongo
    networks:
      development:
    restart: always
    volumes:
      - type: volume
        source: mongo-volume
        target: /data


networks:
  development:

volumes:
  mongo-volume:
