version: "3.1"

services:
  mongoose:
    build:
      context: ./
      target: buildimage
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
      - mongo-admin
    networks:
      development:
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    image: mongo
    networks:
      development:
    ports:
      - 27017:27017
    restart: always
    volumes:
      - type: volume
        source: mongo-volume
        target: /data

  mongo-admin:
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=Password1
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Password1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://admin:Password1@mongo:27017/
    image: mongo-express
    networks:
      development:
    ports:
      - 8081:8081
    restart: always

networks:
  development:

volumes:
  mongo-volume:
